include: package:lint/analysis_options.yaml

linter:
  rules:
   - parameter_assignments

analyzer: 
  errors:
    return_of_invalid_type: info
    argument_type_not_assignable: info
    invalid_assignment: info
    missing_required_param: info
    parameter_assignments: info
    missing_return: info