include: package:lint/analysis_options.yaml

linter:
  rules:
   - parameter_assignments

analyzer: 
  errors:
    argument_type_not_assignable: warning
    invalid_assignment: warning
    missing_required_param: error
    parameter_assignments: error 
    missing_return: error
